untypy.error.UntypyNameError: name 'FooX' is not defined.
Type annotation of class 'Test' could not be resolved.
declared at: test-data/testForwardRef4.py:3
  3 | @record
  4 | class Test:
  5 |     foo: 'FooX'
