untypy.error.UntypyNameError: The name 'Foo' is not defined.
Type annotation of function 'Test.__init__' is not resoveable.
Did you forget importing this type?
test-data/testForwardRef2.py:2
  1 | class Test:
  2 >     def __init__(self, foo: 'Foo'):
  3 |         pass
  4 |     def __repr__(self):
  5 |         return 'Test'
